### ISSUE TITLE
第一次docker-compose up成功了，第二次docker-compose up就报错了

### ISSUE THREAD

**Issue by ganlanshu0211** [copriwolf/docker-lnmp-with-mutli-php-versions#1]
报错如下：
Starting dockerlnmpwithmutliphpversions_php72_1 ... error

Starting dockerlnmpwithmutliphpversions_php56_1 ... error

Starting dockerlnmpwithmutliphpversions_php53_1 ... error

ERROR: for dockerlnmpwithmutliphpversions_php53_1  Cannot start service php53: Cannot link to a non running container: /dockerlnmpwithmutliphpversions_mysql_1 AS /dockerlnmpwithmutliphpversions_php53_1/dockerlnmpwithmutliphpversions_mysql_1

ERROR: for php53  Cannot start service php53: Cannot link to a non running container: /dockerlnmpwithmutliphpversions_mysql_1 AS /dockerlnmpwithmutliphpversions_php53_1/dockerlnmpwithmutliphpversions_mysql_1

ERROR: for php72  Cannot start service php72: Cannot link to a non running container: /dockerlnmpwithmutliphpversions_mysql_1 AS /dockerlnmpwithmutliphpversions_php72_1/mysql

ERROR: for php56  Cannot start service php56: Cannot link to a non running container: /dockerlnmpwithmutliphpversions_mysql_1 AS /dockerlnmpwithmutliphpversions_php56_1/dockerlnmpwithmutliphpversions_mysql_1
ERROR: Encountered errors while bringing up the project.

服务器版本：
centos7.4

**Comment by ganlanshu0211** [comment]
docker-compose restart 就可以了

**Comment by copriwolf** [comment]
👍
