### ISSUE TITLE
mysql容器总是退出

### ISSUE THREAD

**Issue by ganlanshu0211** [copriwolf/docker-lnmp-with-mutli-php-versions#2]
启动之后docker ps -a显示mysql容器已退出
docker-compose restart之后情况还是一样

**Comment by copriwolf** [comment]
你可以尝试
`docker-compose down`,然后`docker images`把构建的映像删除后
`docker-compose up --build`重新构建，如果退出了，可以看看构建过程有没有错误信息

**Comment by ganlanshu0211** [comment]
好吧，我已经用其他仓库了
